/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometricsauthentication;

import javax.swing.JOptionPane;

public class LoginScreen extends javax.swing.JFrame {

    /**
     * Creates new form LoginScreen
     */
    public LoginScreen() {
        initComponents();
        backBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        thumbLen = new javax.swing.JTextField();
        indxFingerLen = new javax.swing.JTextField();
        middleFingerLen = new javax.swing.JTextField();
        indexFingerWidth = new javax.swing.JTextField();
        middleFingerWidth = new javax.swing.JTextField();
        ringFingerWidth = new javax.swing.JTextField();
        pinkieWidth = new javax.swing.JTextField();
        pinkieLen = new javax.swing.JTextField();
        thumbWidth = new javax.swing.JTextField();
        ringDingerLen = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        signupButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("                                                 LOGIN    (Please enter all details in mm)");

        jLabel2.setText("Thumb length");

        jLabel3.setText("Index finger length");

        jLabel4.setText("Middle finger length");

        jLabel5.setText("Ring finger length");

        jLabel6.setText("Pinkie length");

        jLabel7.setText("Thumb width");

        jLabel8.setText("Index finger width");

        jLabel9.setText("Middle finger width");

        jLabel10.setText("Ring finger width");

        loginBtn.setText("login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        cancelBtn.setText("cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        jLabel11.setText("Pinkie width");

        indxFingerLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indxFingerLenActionPerformed(evt);
            }
        });

        ringFingerWidth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ringFingerWidthActionPerformed(evt);
            }
        });

        ringDingerLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ringDingerLenActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        signupButton.setText("sign up");
        signupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(cancelBtn)
                .addGap(18, 18, 18)
                .addComponent(signupButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(middleFingerLen, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(indxFingerLen)
                    .addComponent(ringDingerLen)
                    .addComponent(pinkieLen)
                    .addComponent(thumbWidth)
                    .addComponent(indexFingerWidth)
                    .addComponent(middleFingerWidth)
                    .addComponent(ringFingerWidth)
                    .addComponent(pinkieWidth)
                    .addComponent(thumbLen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backBtn)
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(thumbLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(indxFingerLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(middleFingerLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ringDingerLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinkieLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thumbWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(indexFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(middleFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ringFingerWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pinkieWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelBtn)
                        .addComponent(signupButton))
                    .addComponent(loginBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        try{
            if(thumbLen.getText()!="" && thumbWidth.getText()!=""  &&
                    indxFingerLen.getText()!="" && indexFingerWidth.getText()!="" &&
                    middleFingerLen.getText()!="" && middleFingerWidth.getText()!="" &&
                    ringDingerLen.getText()!="" && ringFingerWidth.getText()!="" &&
                    pinkieLen.getText()!="" && pinkieWidth.getText()!="" ){
               
                String nameOfPerson = BiometricsAuthentication.getInputs(Float.parseFloat(thumbLen.getText()), 
//                BiometricsAuthentication.getInputs(Float.parseFloat(thumbLen.getText()), 
                        Float.parseFloat(thumbWidth.getText()), Float.parseFloat(indxFingerLen.getText()),
                        Float.parseFloat(indexFingerWidth.getText()), 
                        Float.parseFloat(middleFingerLen.getText()), Float.parseFloat(middleFingerWidth.getText()),
                        Float.parseFloat(ringDingerLen.getText()),
                        Float.parseFloat(ringFingerWidth.getText()), Float.parseFloat(pinkieLen.getText()), 
                        Float.parseFloat(pinkieWidth.getText()));
                
                if(nameOfPerson!=""){
                    jLabel1.setText("Welcome "+nameOfPerson);
                    backBtn.setVisible(true);
                    thumbLen.setVisible(false);
                    thumbWidth.setVisible(false);
                    indexFingerWidth.setVisible(false);
                    indxFingerLen.setVisible(false);
                    middleFingerLen.setVisible(false);
                    middleFingerWidth.setVisible(false);
                    ringDingerLen.setVisible(false);
                    ringFingerWidth.setVisible(false);
                    pinkieLen.setVisible(false);
                    pinkieWidth.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel3.setVisible(false);
                    jLabel4.setVisible(false); 
                    jLabel5.setVisible(false);
                    jLabel6.setVisible(false);
                    jLabel2.setVisible(false);
                    jLabel7.setVisible(false);
                    jLabel8.setVisible(false);
                    jLabel9.setVisible(false);
                    jLabel10.setVisible(false);
                    jLabel11.setVisible(false);
                    cancelBtn.setVisible(false);
                    loginBtn.setVisible(false);
                    signupButton.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Not found");
   
                    thumbLen.setText("");
                    thumbWidth.setText("");
                    indexFingerWidth.setText("");
                    indxFingerLen.setText("");
                    middleFingerLen.setText("");
                    middleFingerWidth.setText("");
                    ringDingerLen.setText("");
                    ringFingerWidth.setText("");
                    pinkieLen.setText("");
                    pinkieWidth.setText("");
                }
            }
        }catch(Exception ex){
            
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void indxFingerLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indxFingerLenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indxFingerLenActionPerformed

    private void ringDingerLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ringDingerLenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ringDingerLenActionPerformed

    private void ringFingerWidthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ringFingerWidthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ringFingerWidthActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        thumbLen.setText("");
        thumbWidth.setText("");
        indexFingerWidth.setText("");
        indxFingerLen.setText("");
        middleFingerLen.setText("");
        middleFingerWidth.setText("");
        ringDingerLen.setText("");
        ringFingerWidth.setText("");
        pinkieLen.setText("");
        pinkieWidth.setText("");
        signupButton.setVisible(true);
        
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        thumbLen.setText("");
        thumbWidth.setText("");
        indexFingerWidth.setText("");
        indxFingerLen.setText("");
        middleFingerLen.setText("");
        middleFingerWidth.setText("");
        ringDingerLen.setText("");
        ringFingerWidth.setText("");
        pinkieLen.setText("");
        pinkieWidth.setText("");
         jLabel1.setText("                                                 LOGIN    (Please enter all details in mm)");
        thumbLen.setVisible(true);
        thumbWidth.setVisible(true);
        indexFingerWidth.setVisible(true);
        indxFingerLen.setVisible(true);
        middleFingerLen.setVisible(true);
        middleFingerWidth.setVisible(true);
        ringDingerLen.setVisible(true);
        ringFingerWidth.setVisible(true);
        pinkieLen.setVisible(true);
        pinkieWidth.setVisible(true);
        jLabel2.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
           jLabel2.setVisible(true);
            jLabel7.setVisible(true);
             jLabel8.setVisible(true);
             jLabel9.setVisible(true);
              jLabel10.setVisible(true);
               jLabel11.setVisible(true);
               cancelBtn.setVisible(true);
               loginBtn.setVisible(true);
            signupButton.setVisible(true);
        
    }//GEN-LAST:event_backBtnActionPerformed

    private void signupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupButtonActionPerformed
        this.setVisible(false);
        new signup().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_signupButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField indexFingerWidth;
    private javax.swing.JTextField indxFingerLen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBtn;
    private javax.swing.JTextField middleFingerLen;
    private javax.swing.JTextField middleFingerWidth;
    private javax.swing.JTextField pinkieLen;
    private javax.swing.JTextField pinkieWidth;
    private javax.swing.JTextField ringDingerLen;
    private javax.swing.JTextField ringFingerWidth;
    private javax.swing.JButton signupButton;
    private javax.swing.JTextField thumbLen;
    private javax.swing.JTextField thumbWidth;
    // End of variables declaration//GEN-END:variables
}
